[tool.ruff]
extend-exclude = [
    "setup.py",
    ]    
extend-include = ["*.ipynb"]
select = ["E4", "E7", "E9", "F", "I", "N81", "D2", "D3", "D4", "UP"]
ignore = ["D203", "D206", "D213", "D300", "D415", "N813"]
