# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/qagmire',
                'doc_host': 'https://bamford.github.io',
                'git_url': 'https://github.com/bamford/qagmire',
                'lib_path': 'qagmire'},
  'syms': {'qagmire.core': {'qagmire.core.foo': ('core.html#foo', 'qagmire/core.py')}}}
